FROM example-1---hello-world---rrsim2:latest
RUN mkdir /mas/application/.ssl
COPY cacerts /mas/application/.ssl/cacerts
COPY applicationContext-appsymphonyBeans.xml /mas/application/applicationContext-appsymphonyBeans.xml
